import React, { Component } from 'react';

export default class MainWrapper extends Component {
    render() {
      return (
          <div className="main__wrapper">
              <p className="main__content">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Numquam qui repudiandae necessitatibus nobis voluptate quisquam error. Assumenda ad illum unde atque reiciendis natus facere quam explicabo quasi reprehenderit harum rerum libero, maiores molestias cumque, vero facilis tempora praesentium. Exercitationem reiciendis sapiente illum vel dignissimos sint sequi, nemo quibusdam. Culpa ad ea quod iure provident voluptate vero esse dolore reiciendis deleniti minus, ipsum quos aperiam veniam dolorem? Laborum, voluptatibus? Quasi recusandae deserunt eveniet voluptate ad voluptatum ratione, obcaecati quos est blanditiis. Ut pariatur soluta consectetur accusamus similique eligendi nobis fugit, suscipit explicabo esse beatae repellendus fugiat ullam consequatur adipisci! Quibusdam ad rem, fugiat exercitationem iste consectetur molestiae fuga magni, consequuntur, hic similique officia a qui voluptatem? Impedit accusamus voluptas sapiente aperiam ab odio, magni culpa reiciendis ad maiores mollitia atque accusantium aut inventore fugit provident voluptates, neque delectus ipsa! Fuga beatae vitae placeat, et dolores, voluptatum deserunt voluptate, labore ipsum nisi voluptates quibusdam explicabo accusantium cupiditate laboriosam neque ipsam rerum sed sit consectetur ut dignissimos aut. Dolore reiciendis dicta dignissimos temporibus nam magnam eveniet neque ab sed, itaque consectetur. Est voluptatum sint reprehenderit temporibus veritatis ad repudiandae earum? Sequi, debitis iste doloribus architecto consectetur maxime, similique consequuntur odit laboriosam eveniet dolorem.
              </p>
              <br/>
              <p className="main__content">
                Lorem ipsum, dolor sit amet consectetur adipisicor. Assumenda ad illum unde atque reiciendis natus facrum rerum libero, maiores molestias cumque, vero facilis tempora praesentium. Exercitationem reiciendis sapiente illum vel dignissimos sint sequi, nemo quibusdam. Culpa ad ea quod iure provident voluptate vero esse dolore reiciendis deleniti minus, ipsum quos aperiam veniam dolorem? Laborum, voluptatibus? Quasi recusandae deserunt eveniet voluptate ad voluptatum ratione, obcaecati quos est blanditiis. Ut pariatur soluta consectetur accusamus similique eligendi nobis fugit, suscipit explicabo esse beatae repellendus fugiat ullam consequatur adipisci! Quibusdam ad rem, fugiat exercitationem iste consectetur molestiae fuga magni, consequuntur, hic similique officia a qui voluptatem? Impedit accusamus voluptas sapiente aperiam ab odio, magni culpa reiciendis ad maiores mollitia atque accusantium aut inventore fugit provident voluptates, neque delectus ipsa! Fuga beatae vitae placeat, et dolores, voluptatum deserunt voluptate, labore ipsum nisi voluptates quibusdam explicabo accusantium cupiditate laboriosam neque ipsam rerum sed sit consectetur ut dignissimos aut. Dolore reiciendis dicta dignissimos temporibus nam magnam eveniet neque ab sed, itaque consectetur. Est voluptatum sint reprehenderit temporibus veritatis ad repudiandae earum? Sequi, debitis iste doloribus architecto consectetur maxime, similique consequuntur odit laboriosam eveniet dolorem.
              </p>
              <br/>
              <p className="main__content">
                Lorem atque reiciendis natus facere quam explicabo quasi reprehenderit harum rerum libero reiciendis sapiente <br/> illum vel dignissimos sint sequi, nemo quibusdam. Culpa ad ea quod iure provident voluptate vero esse dolore reiciendis deleniti minus, ipsum quos aperiam veniam dolorem? Laborum, voluptatibus? Quasi recusandae deserunt eveniet voluptate ad voluptatum ratione, obcaecati quos est blanditiis. Ut pariatur soluta consectetur accusamus similique eligendi nobis fugit, suscipit explicabo esse beatae repellendus fugiat ullam consequatur adipisci! Quibusdam ad rem, fugiat exercitationem iste consectetur molestiae fuga magni, consequuntur, hic similique officia a qui voluptatem? Impedit accusamus voluptas sapiente aperiam ab odio, magni culpa reiciendis ad maiores mollitia atque accusantium aut inventore fugit provident voluptates, neque delectus ipsa! Fuga beatae vitae placeat, et dolores, voluptatum deserunt voluptate, labore ipsum nisi voluptates quibusdam explicabo accusantium cupiditate laboriosam neque ipsam rerum sed sit consectetur ut dignissimos aut. Dolore reiciendis dicta dignissimos temporibus nam magnam eveniet neque ab sed, itaque consectetur. Est voluptatum sint reprehenderit temporibus veritatis ad repudiandae earum? Sequi, debitis iste doloribus architecto consectetur maxime, similique consequuntur odit laboriosam eveniet dolorem.
              </p>
          </div>
      );
    }
  }